import React from 'react';
import { HelpCircle, X, Layers, ShieldCheck, Activity, Terminal } from 'lucide-react';
import '../styles/GitPulse/GitPulseHelpModal.css';

const GitPulseHelpModal = ({ show, onClose }) => {
  if (!show) return null;

  return (
    <div className="help-modal-overlay">
      <div className="help-modal-content">
        <div className="help-modal-header">
          <h2 className="help-modal-title">
            <HelpCircle className="text-indigo-600" /> Metrics Guide
          </h2>
          <button onClick={onClose} className="help-modal-close">
            <X size={24} />
          </button>
        </div>
        <div className="help-modal-body">
          <div className="help-section">
            <h3 className="help-section-title">
              <Layers size={18} className="text-indigo-500" /> AST Nodes
            </h3>
            <p className="help-section-text">
              An Abstract Syntax Tree (AST) is a mathematical representation of code. <strong>Old Nodes</strong> measure the code's complexity before a commit, while <strong>New Nodes</strong> measure it after. This allows us to track exact structural growth rather than just "lines of code."
            </p>
          </div>
          <div className="help-section">
            <h3 className="help-section-title">
              <ShieldCheck size={18} className="text-emerald-500" /> Integrity Score Calculation
            </h3>
            <p className="help-section-text">
              The engine uses the Zhang-Shasha algorithm to calculate the <strong>Tree Edit Distance</strong> (the effort required to change the Old AST into the New AST). The Integrity Score ($r$) normalizes this distance from 0 to 1. A sudden, massive injection of nodes without gradual human edits yields a low score.
            </p>
          </div>
          <div className="help-section">
            <h3 className="help-section-title">
              <Activity size={18} className="text-blue-500" /> Score Benchmarks
            </h3>
            <div className="help-benchmark-grid">
              <div className="help-benchmark-item help-benchmark-authentic">
                <strong>0.85 - 1.00 (Authentic):</strong> Steady, human-paced development.
              </div>
              <div className="help-benchmark-item help-benchmark-standard">
                <strong>0.45 - 0.84 (Standard):</strong> Normal feature additions.
              </div>
              <div className="help-benchmark-item help-benchmark-suspect">
                <strong>0.00 - 0.44 (Suspect):</strong> Anomalous dumps (likely AI-generated or copy-pasted).
              </div>
            </div>
          </div>
          <div className="help-section">
            <h3 className="help-section-title">
              <Terminal size={18} className="text-slate-700" /> Raw CST Fragment
            </h3>
            <p className="help-section-text">
              The Concrete Syntax Tree (CST) fragment is the raw grammar output generated by our parsers. It strips away formatting and exposes how the machine interprets the logic. It is the immutable forensic proof used to calculate the edit distance.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GitPulseHelpModal;
